Rework order of testing phases in password setting.
If factory or user password in GP is found, use it!
If GP or files were not found, controller serial number are taken into
account.

diff --git a/unipi/unipi-default-password/unipi-defpass b/unipi/unipi-default-password/unipi-defpass
--- a/unipi/unipi-default-password/unipi-defpass
+++ b/unipi/unipi-default-password/unipi-defpass
@@ -4,7 +4,7 @@ unipi_password_set() {
     PWD_HASH_SET=$1
     
     if [ "$PWD_HASH_SET" = "legacy" ]; then
-		# shellcheck disable=SC2016 # $ is supposed to be in the hash
+	# shellcheck disable=SC2016 # $ is supposed to be in the hash
         usermod ${USER_TARGET} -p '$y$j9T$pi9lbl3bLQsb2OYu5G/7d1$7A8hVYSxM.RSbyaSbVNSvKrf2Eh3woivl2SE1gfFl79'
     else
         usermod ${USER_TARGET} -p "$PWD_HASH_SET"
@@ -47,27 +47,38 @@ unipi_hash_set() {
 
     if [ ! -b "$GPP" ]; then
         echo "Error: GPP does not exist."
-        exit 1
+        return 1
     fi
 
-	# shellcheck disable=SC2064 # $ it is desire to be expanded now
-    trap "umount $GPPMT && rmdir $GPPMT" EXIT
-    mount -o ro,noload $GPP $GPPMT --mkdir
-    
+    if ! mount -o ro,noload $GPP $GPPMT --mkdir; then
+        echo "Error: GPP not formated."
+        return 1
+    fi
+
+    pwd=""
+    force_change=""
     if [ -f $GPPMT/PWD_HASH_USER ]; then
-        unipi_password_set "$(cat $GPPMT/PWD_HASH_USER)"
-    elif [ -f $GPPMT/PWD_HASH_FACTORY ]; then
-        unipi_password_set "$(cat $GPPMT/PWD_HASH_FACTORY)" "1"
+        pwd="$(cat $GPPMT/PWD_HASH_USER)"
+    fi
+    if [ -z "$pwd" ] && [ -f $GPPMT/PWD_HASH_FACTORY ]; then
+        pwd="$(cat $GPPMT/PWD_HASH_FACTORY)"
+        force_change="1"
+    fi
+    if [ -n "$pwd" ]; then
+        unipi_password_set "$pwd" "$force_change"
     else
         echo "Error: no password for user unipi specified in image or GPP."
-        exit 1
     fi
+    umount $GPPMT && rmdir $GPPMT
+    if [ -z "$pwd" ]; then
+        return 1
+    fi
+    return 0
 }
 
 
 USER_TARGET="unipi"
 USER_LINE=$(getent shadow "${USER_TARGET}")
-UNIPI_SN="$(cat /run/unipi-plc/unipi-id/product_serial)"
 
 # Check if user unipi exists
 if [ -z "$USER_LINE" ]; then
@@ -86,15 +97,19 @@ case "$PWD_HASH_OLD" in
     ;;
 esac
 
+if unipi_hash_set; then
+    exit 0
+fi
+
+UNIPI_SN="$(cat /run/unipi-plc/unipi-id/product_serial)"
 unipi_sn_check "$UNIPI_SN"
 
 case "$?" in
     "0")
-        unipi_hash_set
     ;;
     "1")
         echo "Error: Invalid SN, no password is set for user unipi."
-		exit 1
+	exit 1
     ;;
     "2")
         unipi_password_set "legacy" "1"
